### ISSUE TITLE
Not working properly with dynamic content

### ISSUE THREAD

**Issue by iskrenpanteleev** [jekuer/add-to-calendar-button#12]
Currently, I am using the library with AngularJS. One of the add-to-calendar buttons is rendered on page load but the others are loaded dynamically after "ng-repeat" finishes.
The issue is that one of the buttons is already rendered and has the assigned ID of 0 (from the library). However when the other buttons are rendered, the first button HTML class - .atcb is already processed by the library and gone. The library does not see it as an add-to-calendar button, therefore the IDs of the buttons start back from 0 to n.
This problem causes the following functionality disruption.
After clicking the first button in the ng-repeat, it calls the first button on the page which was generated on the initial page load.
I've created a temporary fix by generating random IDs and not relying on the plugin count of .atcb elements to assign the IDs.
Inside the function atcb_init(), where the btnID is assigned, I've changed it to use a random number instead of the count.
`var btnId = Math.floor(Math.random() * 1000) + 1;`

![Screenshot 2021-12-20 at 17 19 08](https://user-images.githubusercontent.com/29824159/146913791-6e22d65d-9fc0-40be-95e9-4f36bcfe0357.png)

**Comment by jekuer** [comment]
Thanks for the observation!
Should be fixed with new version 1.3.1, where we basically also count already existing ones, when generating new ones.
**Would love to hear your test result!**
