### ISSUE TITLE
Schema.org Event markup compatibility

### ISSUE THREAD

**Issue by p-w** [jekuer/add-to-calendar-button#13]
@jekuer, thank you for publishing the _add-to-calendar-button_-library, I love it!

To achieve compatibility with the [schema.org Event markup](https://schema.org/Event) it would be awesome to enhance you parser accordingly.

The JSON markup could be something like:
```
<div class="atcb">
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "TouristAttraction",
    "name":"Reminder to check the add-to-calendar-button repo",
    "description":"Check out the maybe easiest way to include add-to-calendar-buttons to your website at: https://github.com/jekuer/add-to-calendar-button",
    "event": {
    "@type": "Event",
    "startDate":"01-14-2022",
    "endDate":"01-18-2022",
    "startTime":"10:15",
    "endTime":"23:30",
    "location":"World Wide Web"
    },
    "options":[
    "Apple",
    "Google",
    "iCal",
    "Microsoft365",
    "Outlook.com",
    "Yahoo"
    ],
    "timeZone":"Europe/Berlin",
    "iCalFileName":"Reminder-Event"
  }
  </script>
</div>
```

Adding the ld+json script tag would allow you to remove the ```style="display:none;"``` altogether, too.

The javascript code could be enhanced to look for a ```script```-child element and use that in case of existence, like:
```
let atcButtons = document.querySelectorAll('.atcb');
// ... and generate the buttons one by one
for (let i = 0; i < atcButtons.length; i++) {
  let atcbConfig;
  // check if schema.org markup is present
  let schema = atcButtons[i].querySelector('script');
  // get their JSON content first
  if (schema && schema.innerHTML) {
    // get schema.org event markup
    atcbConfig = JSON.parse(schema.innerHTML);
  } else {
    // get JSON from HTML block
    atcbConfig = JSON.parse(atcButtons[i].innerHTML);
  }
  // ...
}
```

The [schema.org validator](https://validator.schema.org/) will still highlight some compatibility issues regarding to unkown attributes, but the Googlebot should be able to index the content.

**Comment by jekuer** [comment]
What an honor to see you here, @p-w ;).
Sounds good. I would still try to achieve some backwards compatibility - especially since the schema.org would not work with dynamic dates (e.g. the magic placeholder "today").

One question though: Setting a parent schema feels a little bit complicated. Why not simply:

```{
  "event": {
    "@context": "https://schema.org",
    "@type": "Event",
    "name":"Reminder to check the add-to-calendar-button repo",
    "description":"Check out the maybe easiest way to include add-to-calendar-buttons to your website at: https://github.com/jekuer/add-to-calendar-button",
    "startDate":"01-14-2022",
    "endDate":"01-18-2022",
    "startTime":"10:15",
    "endTime":"23:30",
    "location":"World Wide Web"
  },
  "options":[
    "Apple",
    "Google",
    "iCal",
    "Microsoft365",
    "Outlook.com",
    "Yahoo"
  ],
  "timeZone":"Europe/Berlin",
  "iCalFileName":"Reminder-Event"
}

**Comment by p-w** [comment]
> One question though: Setting a parent schema feels a little bit complicated. Why not simply:
> 
> ```
>   "event": {
>     "@context": "https://schema.org",
>     "@type": "Event",
>     "name":"Reminder to check the add-to-calendar-button repo",
>     "description":"Check out the maybe easiest way to include add-to-calendar-buttons to your website at: https://github.com/jekuer/add-to-calendar-button",
>     "startDate":"01-14-2022",
>     "endDate":"01-18-2022",
>     "startTime":"10:15",
>     "endTime":"23:30",
>     "location":"World Wide Web"
>   },
>   "options":[
>     "Apple",
>     "Google",
>     "iCal",
>     "Microsoft365",
>     "Outlook.com",
>     "Yahoo"
>   ],
>   "timeZone":"Europe/Berlin",
>   "iCalFileName":"Reminder-Event"
> }
> ```

Working with different data types, i.e. JSON, directly in HTML could cause some rendering engines and bots to fail. Clearly specifying which content holds with type of data can be a good practice but it's not a must.

The schema.org validator wasn't able to detect the markup within a non-declarded JSON context during my tests, so it would be worthless for SEO and ranking purposes.
Probably I've overlooked something, if so I'd be happy for a hint.

**Comment by jekuer** [comment]
Sorry for the confusion. 
I actually was only referring to the JSON structure - not the script tag (I only left it out for a better overview).
There, I would have moved "name" and "description into the event block and also put the "@context" there. This way, a user would not have to break his/her head about whether its a "TouristAttraction" or something else.
And it throws less errors that way ;).
_(I will update my comment above)_

**Comment by jekuer** [comment]
Updated with v1.4.0 - now even without any warnings, if you place the time within the startDate and endDate ;).
