### ISSUE TITLE
The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by gkkirilov** [jekuer/add-to-calendar-button#16]
As I am using some Cyrillic symbols I had to add this inside the btoa method this code
`
.replace(/[\u00A0-\u2666]/g, function(c) {
    return '&#' + c.charCodeAt(0) + ';';
})
`

**Comment by jekuer** [comment]
@gkkirilov , does this cover all relevant cyrillic symbols? Do you want to push a Pull Request for that?

**Comment by gkkirilov** [comment]
I think it does, but don't want to add more complexity to the library, maybe lets just leave it as a reference point if anyone needs it.

**Comment by jekuer** [comment]
I included your fix in the latest version. It is not ideal, but at least removes the console error. Left a comment in the code for future optimization.
