### ISSUE TITLE
On mouse enter the popuo show and close very fast.

### ISSUE THREAD

**Issue by robertaonnis** [jekuer/add-to-calendar-button#21]
There is one point of atcb.js

`bgOverlay.addEventListener('mouseenter', atcb_close_all, false);`

during the transiction of the mouse the system continous open the popup. SHould be a system that open and close on on mouse out of the div and not for all the transiction.

**Comment by robertaonnis** [comment]
Solution you can sobstitute this:
`  bgOverlay.addEventListener('mouseenter', atcb_close_all, false);`

with:
`  bgOverlay.addEventListener('mouseleave', atcb_close_all, false);`

**Comment by jekuer** [comment]
Was built that way to work via the same process with a mouse device as well as with a touch device. Mouseout with touch is imho not very reliable.
There could be an option to have both, a mouseout of the div + a tap event on the bgoverlay, but you first need to convince me why that would be better - or why the current solution realy is a problem ;)
