### ISSUE TITLE
Location not adding to Google Calendar app [iPhone Only]

### ISSUE THREAD

**Issue by mlidsky** [jekuer/add-to-calendar-button#24]
When selecting the 'Google' option from the Add to Calendar dropdown, the 'Location' field is not being set in the Google Calendar app on iPhone. If the Google Calendar application is not installed on the device, the Calendar is opened in the Browser and is set appropriately.

Issue is not reproducible on Desktops or Android devices. I have tested with the iCal and Apple options and Location is set as expected. All other values (Name, Description, Start/End Date+Times) seem to set as expected within Google Calendar.

Test Site: https://www.musicofdenver.com/

Replication Steps:
1) Install Google Calendar application on iPhone
2) Navigate to and select 'Add to Calendar' button
3) Select 'Google' option
4) Observe Location field is empty in Google Calendar app

**Comment by jekuer** [comment]
@mlidsky , Thanks for your observation. Can you share more details on your iphone (model, iOS Version)?

**Comment by mlidsky** [comment]
I've replicated with:
iPhone 13 Pro / iOS 15.2.1
iPhone 8 Plus / iOS 15.2.1

Both instances, Google Calendar v22.1.1

**Comment by jekuer** [comment]
#43 is solved, but I think this here is another issue. Still needs investigation (even I am quite sure that there is no stable fix for that). Only thing I have in mind so far is adding the location also to the description, when identifying iOS and only for the Google option.

**Comment by jekuer** [comment]
Investigated this for a while and found no stable solution, since this happens with basically all implementations.
So, for now, I've created a workaround (in v.1.8), which simply adds the location to the description, if the user is on an iOS device and using the Google calendar option.
