### ISSUE TITLE
Feature request: event reminder parameter 

### ISSUE THREAD

**Issue by bipulluitel** [jekuer/add-to-calendar-button#26]
It would be nice to add event reminder parameters in the .ics file and on the Google Calendar:
Something like this on the .ics file:

```
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:REMINDER
TRIGGER:-PT15M
END:VALARM
```
Google's add event URL may also have some paramters to pass the reminder info.

**Comment by jekuer** [comment]
I would argue that this should be something 100% controlled by the user (who owns the calendar).
For example, in most calendars you can set your default reminder behaviour. And you can always change this per event.
Should not be something, the issuer of an event defines - even I understand that this might be a wished for functionality.
Therefore, I will close this issue, but feel free to change my mind :).

**Comment by bipulluitel** [comment]
I agree, the reminder is something the user "can" always control. But take an appointment for example. If my website is offering a way for users to book an appointment and download that event, it would be nice to set a reminder (let's say 2 hours ahead of time) by default. In my use case, users always wants a reminder for their event. Of course they could decide to override it, change or turn it off entirely. But as a event provider, i feel like being able to set a default reminder would be a useful feature. 
But I understand if you decline it.

**Comment by jekuer** [comment]
Understood. I would agree completely, if the event would get directly created in the calendar. However, since it always opens the "new event" screen (no matter the calendar), the user gets his default setting their and can define it as he/she wants.
Feels more user-friendly to me at the moment - therefore I would pause it for now - not saying forever ;).
