### ISSUE TITLE
issue with the accents like è being converted to &#233;

### ISSUE THREAD

**Issue by woluweb** [jekuer/add-to-calendar-button#32]
Hi,

If I type "è" in the Name, Description or Location, it gets "converted" to `&#233;`
So I don't see how to allow accents in those fields.
Txs :)

**Comment by jekuer** [comment]
This should only be the case for the ics file (iCal). Might be related to #16 .

**Comment by woluweb** [comment]
Sorry, I forgot to mention.
Indeed, it was for the ics files.
For Google for example it is OK (I did not test the other ones since I don't have calendars on those platforms :) )

I guess it is related to all characters with accents etc.

**Comment by woluweb** [comment]
And most importantly, I forgot also to first mention that your tool is *really* **really** great! ;)

**Comment by jekuer** [comment]
Solved with v1.6.0
