### ISSUE TITLE
width of Microsoft Teams icon (really a tiny tiny "issue")

### ISSUE THREAD

**Issue by woluweb** [jekuer/add-to-calendar-button#38]
It is really a detail (I hardly dare posting about it :) ), but I have noticed that the icon for Microsoft Teams is a little bit wider than all the other ones. Consequence: the text next to the icons is aligned for all... except Microsoft Teams.

Well, don't make a new release just for that obviously :D

**Comment by jekuer** [comment]
It's not only that one ;).
Solution will be giving the icon container a width of 18px. Will keep it in mind, but need to test it a little bit further for compatibility and responsive behavior.

**Comment by woluweb** [comment]
Speaking about style, everybody can of course override the original css, but if I may suggest something:

When Active, the button gets a bigger margin and/or padding.
In real life, that is not really nice bc it moves slightly downwards the content of the website being _after_ the button.
A kind of "hickup".
So playing with background color, border-color, box-shadow etc is fine. But probably not padding & margin.
My 2 cents.

**Comment by jekuer** [comment]
@woluweb , the margin/padding manipulation is done on purpose to support the "pop" effect. However, it should not move content after the button (it adds padding, while removing margin accordingly).

If you experience this behavior, I would definitely consider it a bug. 

Could you add, which browser (and OS) you are using, if the demo page buttons (https://jekuer.github.io/add-to-calendar-button/) show the same behavior on your side, and whether you are using the inline option or not?
Thanks a lot in advance!!
