### ISSUE TITLE
Update README/Troubleshoot

### ISSUE THREAD

**Issue by slackday** [jekuer/add-to-calendar-button#43]
Hello,

Thanks for a great plugin!

I spend a good few hours chasing a but why buttons didn't work in on iOS. The error was json parse error. I have description texts with line-breaks, emails url/links etc.

After trying a few good things with no solution I found it was iOS format detection causing problems. 

Adding these meta tags 

```
<meta name="format-detection" content="telephone=no">
<meta name="format-detection" content="date=no">
<meta name="format-detection" content="address=no">
```

on pages with add-to-calendar-button solves the problem. Obviously it will break iOS creating links on other content on the page. So not the best solution maybe.

Anyway I'm leaving this info here for anyone else having problems. Maybe we could add a "Tips" or troubleshooting section to the README.

Sorry I'm creating this as an issue rather than a pull-request with README update but I don't have time to make a PR at the moment.

**Comment by jekuer** [comment]
Awesome catch!
Maybe we need to drop the JSON approach in the future 😅🙈.

One question though: Did it affect all of the mentioned elements or only one and you included the others for consistency?

**Comment by jekuer** [comment]
And one quick thought. Maybe it is enough to strip out all <a> tags (not the text) before parsing the JSON.

**Comment by jekuer** [comment]
Hi @slackday ,
latest version 1.7.5 strips out HTML tags (except <br>) from the JSON before parsing it. It therefore also successfully cleans up the Apple-Safari mess.
Worked on my side. Maybe you could re-test.
