### ISSUE TITLE
Error when parsing time and date in the same value

### ISSUE THREAD

**Issue by houmark** [jekuer/add-to-calendar-button#44]
Hi there,

Thanks for this. Using this with React and noticed that a date and time in the same field seems to not work as intended (or we are doing something wrong or documentation is wrong).

I created a Code Sandbox example here, please see both event objects inside App.js:
https://codesandbox.io/s/charming-frost-8g7qvz?file=/src/App.js

Click either button and for example "Google" to see the error:
RangeError
Invalid time value

Also, the second button may not be supported at this time, but if that's the case, then it would be really nice to have support for a full date/timestamp including milliseconds and Z so that we can avoid parsing on the date when pulling it from the database.

**Comment by jekuer** [comment]
Short answer: Those are no valid dates. The first one is supported by the schema.org style (that's the documentation part you are referring to), which you do not use. Therefore, both not valid.

However, we could extend the parsing to support those edge cases. Basically stripping out milliseconds early and trying the date+time in case we find a delimiter.
In addition, we should optimize later parsing (the clean up job then).
Con: It costs performance (not much of course) on the button side and therefore for many users, while the same could be easily done on host-application side in the rather rare cases where it is necessary.

I tend to include it. But would have low priority to me.
**To speed it up - as always: Open for merge requests!**

**Comment by houmark** [comment]
I know they are not valid dates, but I was using the documentation to at least get the first example to work. But in that case the documentation is either wrong or unclear here:
https://github.com/jekuer/add-to-calendar-button#full-structure-with-schemaorg-markup

Do I need to use the entire schema.org markup in order to use the T delimiter?

We are using separate time values, which works but requires parsing on our end, which is not a big deal as we have date libraries ready to do so, but it would of course be nicer to be able to just pass the value along.

**Comment by jekuer** [comment]
@houmark , theoretically yes.
However, I added a cleanup job in the lates v1.7.4, which cleans such date strings and also allows for the T delimiter outside of the schema.org implementation.
It is more of a fallback solution rather than a new official way of doing things. But hopefully should help you with your project! :)

**Comment by houmark** [comment]
Hey! Thanks for the update.

I can confirm that it works with the format I exampled using just one field for the date and time. Formatting the date and time in our app using multiple fields and timeZone also worked, so this was not blocking for us and I am not totally sure if we prefer one or the other. Setting the exact time in its own field and applying the time zone seems safer, but outputting GMT in one field seems to produce the same result now, so this just makes this package more flexible for everyone :)
