### ISSUE TITLE
Error importing css file when using react

### ISSUE THREAD

**Issue by daniellin215** [jekuer/add-to-calendar-button#45]
Hi, I have a next.js react app with a global.css file. In my global.css file, when I try to import the css file, `@import "add-to-calendar-button/assets/css/atcb.min";` I get the following error: `Package path ./assets/css/atcb.min is not exported from package /Users/daniellin/Documents/<project-name>/node_modules/add-to-calendar-button (see exports field in /Users/daniellin/Documents/<project-name>/node_modules/add-to-calendar-button/package.json)`

Wondering if there is a way to address this issue? Basically what is happening is when I click on the button, the dropdown opens but it takes up the entire screen currently... So I try to import the css file to see if this will solve the issue. My component is the same as the `atcb_action` example.

**Comment by jekuer** [comment]
@daniellin215 , fixed with new version 1.7.3 .
Thanks for the catch! This was a quite new behavior of the React setup being more picky on the module config.
