### ISSUE TITLE
How to customize the init hook

### ISSUE THREAD

**Issue by albertosgz** [jekuer/add-to-calendar-button#5]
First of all, thanks for you work, is awesome!

Is possible to customize the hook where to initialize? For what I understood from docs, the point is:
`class="atcb"`

What about if the same page we have more than one "Add to Calendar" buttons?

**Comment by jekuer** [comment]
I am not exactly sure what you mean.
You can add as many buttons as you want. They all simply need the class "atcb".
The init happens via an event listener after the page has been loaded (might differ when going with the npm solution). On init, it scans the whole page for placeholders and replaces them one by one.

**Comment by albertosgz** [comment]
You're right, it is me, I didn't understand well. I was thinking how to customize each button without parameters in `atcb_init`, but are in the template itself. Thanks anyway for your quick response!
