### ISSUE TITLE
Uncaught ReferenceError: isiOS is not defined

### ISSUE THREAD

**Issue by cggit** [jekuer/add-to-calendar-button#55]
Hi,

Not sure if it's something specific to me but I get "Uncaught ReferenceError: isiOS is not defined" on OSX 10.14.6 in lastest Chrome, Firefox and Safari when trying to click add to Google Calendar. I have the issue in my implementation and the demo.

For some reason changing const isiOS to var isiOS fixes it...

Thanks for the time saving script.

**Comment by jekuer** [comment]
Fixed with 1.8.2
