### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by JesusKhero** [jekuer/add-to-calendar-button#61]
Is there any posibility on add recurring events on calendars?
like: repeats every Monday
Google calendars links seems to support them.

**Comment by joekim** [comment]
What needs to happen for this to work?

**Comment by jekuer** [comment]
Investigation regarding the support and approaches for all supported calendar types. Plus somebody finding the time to implement it. :)
So, will happen in the future. The more dev support, the earlier.

**Comment by jekuer** [comment]
Implemented with the latest 1.11 release - feel free to check it out and report any issues! :)
At the moment, we only support the input of RRULE rules. Mind that recurring events limit the selection of calendars.
One known and not yet fixed issue are recurring events, which happen over a change of Summer/Winter time. This would not adapt correctly at the iCal version. It needs a way more complex ics file generation, which will take more time to implement (but it's on the roadmap).
