### ISSUE TITLE
blur

### ISSUE THREAD

**Issue by Zeusakos** [jekuer/add-to-calendar-button#62]
Hello, and congrats for this feature. I have a question in Apple devises if i have more than one add to calendar buttons, when one is active the others doesn't blur, and the active one doesn't cover the other. Is it a known bug or maybe there is a solution for this?

Sorry for my english, thanks in advance

**Comment by jekuer** [comment]
What version are you running?
Do you experience the same behavior at the demo page?
If yes, what iOS version and which browser are you using?
Thanks!

**Comment by Zeusakos** [comment]
I am running  1.8.6. Yes in the demo page it still doesn't blur out the other buttons, tried in both google and safari the version is 15.5.

**Comment by Zeusakos** [comment]
Hello again i managed to solve my problem by putting this line in my css atcb_button and atcb_list 
**-webkit-transform: translate3d(0,0,0);.**
And again congrats for the feature 🥇

**Comment by jekuer** [comment]
Thanks for the debugging. I will optimize this a little bit further in the near future. Therefore, I would leave the ticket open for the moment.
