### ISSUE TITLE
Feature Request: Description syntax parse for hyperlink

### ISSUE THREAD

**Issue by trekfan42** [jekuer/add-to-calendar-button#73]
Since the description field in calendar apps generally support hyperlinking text, it would be nice to obfuscate the link behind a defined string.
for example 

description:"
Some info about the event:
Website:
[url]https://github.com/jekuer/add-to-calendar-button [text] View our source [/text][/url]
"

Looks like:
[ View our source
](https://github.com/jekuer/add-to-calendar-button)

**Comment by jekuer** [comment]
Implemented with the latest 1.11 release - feel free to check it out and report any issues! :)
I adapted your suggestion. Scheme would be [url]https://domain.com|Label for the link[/url]

**Comment by trekfan42** [comment]
Thanks so much! 
Too bad It wont work with apple calendar, 

I was hoping to obfuscate the link 

oh well.

**Comment by trekfan42** [comment]
is the " | " that is the special character that is causing the issue with those platforms?

**Comment by jekuer** [comment]
Apple requires an ics file. Those files have their problems with html. That's why we did not support it so far and that's the reason the text is not showing up.

There is some potential way and I will dig into it in the near future.

**Comment by jekuer** [comment]
@trekfan42 , found a fix - will be available with the next release.

**Comment by trekfan42** [comment]
Wow, that was fast, cool!
