### ISSUE TITLE
Customizing buttons view

### ISSUE THREAD

**Issue by anna-visarsoft** [jekuer/add-to-calendar-button#8]
Please, make the option to not use this main button. In my case I need calendar buttons in the row. 
So it will be great to have some options for customizing.

**Comment by RoMay** [comment]
Very needed feature, thank you.

**Comment by jekuer** [comment]
V1.2.0 now supports the argument `"inline":true`, which makes the button appear inline.
You can do more customization on your own, by altering the css file :).
