### ISSUE TITLE
Support hooking into events

### ISSUE THREAD

**Issue by treyhunner** [jekuer/add-to-calendar-button#82]
I'd like to track how many users actually follow through and click on one of the options (and possibly track which option they clicked to see which calendar apps are most relevant to support for my users).

It'd be nice if browser events were triggered when users trigger the widget and (more importantly for me) when users select an option.

**Comment by svchostdotexe** [comment]
love this. we are using our own tracking system. would it be possible to add our own attributes to the buttons via the planned system?

**Comment by jekuer** [comment]
@svchostdotexe , what would be your expectations for that?
Idea: You can define a prefix, which will be added to the class names. Like atcb-PREFIX-Google for the Google option.

**Comment by svchostdotexe** [comment]
just realized those attributes are angular directives and probably not suitable here. i guess we can find a way to implement our tracking to hook into class names as done by other tracking frameworks. will talk to our main engineer as soon as he is back from his holiday!

**Comment by jekuer** [comment]
btw: will be IDs instead of classes - more precise.

**Comment by jekuer** [comment]
Implemented with the latest 1.11 release - feel free to check it out and report any issues! :)
