### ISSUE TITLE
[Bug]: `fill-available` creates warning

### ISSUE THREAD

**Issue by houmark** [jekuer/add-to-calendar-button#89]
### What happened?

The latest CSS change with `fill-available` seems to result in a warning (we are using ATCB in React using CRA).

![CleanShot 2022-07-18 at 15 46 22](https://user-images.githubusercontent.com/467330/179615201-f7bc68de-e690-4f47-be85-39766c090f12.png)

Sorry, I'm not sure what the fix is, but this results in a compile warning on every build, as shown in the screenshot.

### How to reproduce?

Update to latest add-to-calendar-button 1.11.1.

### Screenshots & more

See the screenshot above.

### System & Environment

1. On build
2. Browser not relevant
3. add-to-calendar-button 1.11.1

**Comment by jekuer** [comment]
@houmark , should be fixed with v1.11.2

**Comment by houmark** [comment]
Perfect, thanks for the fast fix. I can confirm we are no longer seeing the warning with 1.11.2.
