### ISSUE TITLE
Angular needs to init in ngAfterViewChecked instead of ngAfterViewInit

### ISSUE THREAD

**Issue by entrifis** [jekuer/add-to-calendar-button#9]
Calling `atcb_init()` in the `ngAfterViewInit` will find no DOM nodes with the button as the DOM is not rendered yet. The function needs to be called in `ngAfterViewChecked` when the buttons are rendered.

**Comment by jekuer** [comment]
@entrifis , please correct me if I'm wrong, but I would say it depends on your app, while I would consider ngAfterViewInit as the best default, since ngAfterViewChecked get's called on every DOM change. This usually is no good idea for an initialization - again, depending on what your app does.

**Comment by entrifis** [comment]
@jekuer you are very correct, I had the button in an `*ngIf` div which was rendered after the initial view was rendered (I had to load something first). I just had to move the init of the calendar button at another point in my component when I knew the condition of the `*ngIf` was determined. `ngAfterViewChecked` is a wrong place to put it, the right place to call the function is when the button is sure to be shown.

**Comment by jekuer** [comment]
I have updated the readme a little bit and also the logic. after rendering the button, the identifying class gets removed from the placeholder. This way, theoretically, you could init as often as you want - without the script going crazy (not saying it is recommended).
